const PLAN = {
  title:'Outdoor Athlete Longevity Plan', version:'1.1',
  sessions:{
    A:{name:'Strength A',subtitle:'Squat • Pull • Core',exercises:[
      ex('Goblet squat → front/safety-bar squat','3 x 6–8','RPE 6–8','90 sec','Smooth depth; knees track over toes'),
      ex('Romanian deadlift','3 x 8','RPE 7','90 sec','Hips back; long spine'),
      ex('Step-up','2–3 x 8/leg','RPE 7','60 sec','Control lowering; whole foot'),
      ex('Lat pulldown or assisted pull-up','3 x 8–10','RPE 7–8','60–90 sec','Shoulders down; chest tall'),
      ex('Seated cable row','3 x 10','RPE 7','60 sec','Pause briefly at ribs'),
      ex('Pallof press','3 x 10/side','Controlled','45 sec','Do not rotate'),
      ex('Farmer carry','3 x 30–45 sec','Challenging','60 sec','Tall posture; strong grip') ]},
    B:{name:'Strength B',subtitle:'Hinge • Push • Carry',exercises:[
      ex('Trap-bar deadlift or kettlebell deadlift','3 x 5–6','RPE 6–8','2 min','Push floor away; no grinding'),
      ex('Split squat','3 x 8/leg','RPE 7','75 sec','Stable knee'),
      ex('DB bench press','3 x 8–10','RPE 7–8','75 sec','Neutral/comfortable wrist'),
      ex('Half-kneeling single-arm cable/DB press','3 x 8/side','RPE 7','60 sec','Ribs down; glute engaged'),
      ex('Face pull','3 x 12–15','Moderate','45 sec','Upper-back control'),
      ex('Dead bug','3 x 6–8/side','Slow','45 sec','Low back controlled'),
      ex('Suitcase carry','3 x 30–45 sec/side','Challenging','45 sec','Do not lean') ]},
    C:{name:'Strength C',subtitle:'Single-Leg • Athletic • Conditioning',exercises:[
      ex('Reverse lunge or supported rear-foot split squat','3 x 8/leg','RPE 7','75 sec','Stable foot and knee'),
      ex('Single-leg RDL','3 x 8/leg','RPE 6–7','60 sec','Square hips; balance first'),
      ex('Cable row or chest-supported DB row','3 x 10','RPE 7','60 sec','Upper-back endurance'),
      ex('Push-up progression','3 sets','RPE 6–8','60 sec','Stop 2–3 reps before failure'),
      ex('Cable chop/lift','3 x 8/side','Controlled','45 sec','Rotate through trunk/hips'),
      ex('Bike/row intervals','6–10 x 30s brisk / 60s easy','Repeatable','—','No all-out sprinting in Phase 1') ]}
  },
  durability:[
    ex('Short-lever Copenhagen plank','2 x 15–30 sec/side','Easy–moderate','30 sec','No sharp groin pain'),
    ex('Controlled lateral lunge / shallow Cossack','2 x 6/side','Easy','30 sec','Comfortable depth'),
    ex('Calf raise','2 x 12–15','Moderate','30 sec','Full controlled range'),
    ex('Tibialis raise','2 x 12–15','Moderate','30 sec','Back to wall if needed'),
    ex('Wrist extension rock','2 x 8–10','Gentle','30 sec','Gradually load palm-down extension'),
    ex('Light wrist flexion/extension','2 x 12–15 each','Light','30 sec','Slow tempo'),
    ex('Forearm pronation/supination','2 x 10/side','Light','30 sec','Light hammer/DB lever'),
    ex('Band external rotation','2 x 12–15','Light','30 sec','Shoulder durability')],
  warmup:['3 min easy bike/rower/treadmill','Thoracic rotations — 6/side','90/90 hip transitions — 6/side','Adductor rock-backs — 8/side','Bodyweight squat — 10','Band pull-aparts/face-pull — 12','Wrist quadruped rocks — 8–10'],
  phases:[
    ['Weeks 1–2','Re-entry','2 working sets on most movements; RPE 6','Leave feeling like you could do more'],
    ['Weeks 3–4','Build consistency','Mostly 3 sets; RPE 6–7','Technique before load'],
    ['Weeks 5–6','Build strength','3 sets; RPE 7','Small load increases only'],
    ['Weeks 7–8','Consolidate','3 sets; RPE 7–8','Protect riding quality'],
    ['Week 9','Deload','Reduce volume ~30–40%','Absorb training'],
    ['Weeks 10–11','Performance build','3 sets; selected load increases','Strong, crisp reps'],
    ['Week 12','Benchmark & reset','Moderate volume; no max testing','Compare consistency/capacity']]
};
function ex(name,prescription,effort,rest,cue){return {name,prescription,effort,rest,cue}}

const REFERENCES = {
  '3 min easy bike/rower/treadmill':ref('Easy cardio warm-up',['Move at a conversational pace for about 3 minutes.','Gradually increase temperature; do not turn it into conditioning.'],'You should feel warmer and looser, not tired.'),
  'Thoracic rotations — 6/side':ref('Thoracic rotation',['Start on hands and knees or in a half-kneeling position.','Place one hand behind your head.','Rotate elbow toward the floor, then open chest toward the ceiling.','Move through your upper back while keeping hips mostly still.'],'Do not force the low back to create the rotation.'),
  '90/90 hip transitions — 6/side':ref('90/90 hip transitions',['Sit with both knees bent roughly 90 degrees.','Keep your torso tall and rotate both knees slowly from one side to the other.','Use your hands for support if needed.'],'Work in a comfortable range; smooth motion matters more than depth.'),
  'Adductor rock-backs — 8/side':ref('Adductor rock-back',['Start on hands and knees.','Extend one leg out to the side with the foot flat or heel down.','Keep a neutral spine and slowly sit hips backward until you feel the inner thigh.','Return forward and repeat.'],'You want a mild stretch/tension, not burning or sharp groin pain.'),
  'Bodyweight squat — 10':ref('Bodyweight squat',['Stand about shoulder-width with toes slightly turned out.','Brace lightly and sit hips down between your feet.','Keep the whole foot in contact with the floor.','Stand by driving the floor away.'],'Knees can move forward; keep them tracking in line with the toes.'),
  'Band pull-aparts/face-pull — 12':ref('Band pull-apart / face pull',['Use a light band.','For pull-aparts, keep arms near shoulder height and spread the band until shoulder blades come together.','For face pulls, pull toward eye/forehead level with elbows high.'],'Keep shoulders away from your ears; this is activation, not a max-strength set.'),
  'Wrist quadruped rocks — 8–10':ref('Wrist quadruped rocks',['Start on hands and knees with palms flat and fingers forward.','Keep elbows straight but not locked.','Slowly shift your shoulders forward until you feel comfortable wrist extension.','Rock back and repeat.'],'Use a pain-free range. The goal is gradual tolerance to loaded wrist extension.'),
  'Goblet squat → front/safety-bar squat':ref('Goblet squat',['Hold a dumbbell or kettlebell vertically against your chest.','Set feet around shoulder width and brace your trunk.','Sit down between your hips while keeping the whole foot planted.','Drive up smoothly without bouncing.'],'Keep knees tracking over toes and stop at the deepest comfortable, controlled position.'),
  'Romanian deadlift':ref('Romanian deadlift',['Hold weights in front of your thighs.','Soften your knees and push hips straight backward.','Keep weights close to your legs and spine long.','Stop when hamstrings are loaded and you can no longer hinge without rounding, then stand tall.'],'This is a hip hinge, not a squat. Do not chase the floor.'),
  'Step-up':ref('Step-up',['Use a box height that lets you control the movement.','Place the entire working foot on the box.','Lean slightly forward and drive through that leg to stand.','Lower slowly without dropping onto the trailing leg.'],'Minimize the push from the floor leg; control the descent.'),
  'Lat pulldown or assisted pull-up':ref('Lat pulldown / assisted pull-up',['Set shoulders down away from ears.','Pull elbows toward your ribs while keeping the chest tall.','Pause briefly, then control the return to full reach.'],'Avoid jerking, swinging, or pulling the bar behind your neck.'),
  'Seated cable row':ref('Seated cable row',['Sit tall with a neutral spine.','Start with arms long and shoulders controlled.','Pull handle toward lower ribs while drawing shoulder blades back.','Pause, then return slowly.'],'Do not turn it into a low-back rocking exercise.'),
  'Pallof press':ref('Pallof press',['Stand or kneel sideways to a cable/band.','Hold handle at your chest and brace.','Press hands straight forward without letting your torso rotate.','Return under control.'],'The resistance should try to rotate you; your job is to stay square.'),
  'Farmer carry':ref('Farmer carry',['Hold heavy dumbbells or kettlebells at your sides.','Stand tall with ribs stacked over pelvis.','Walk with controlled steps and strong grip.'],'Do not shrug or lean; think tall and quiet.'),
  'Trap-bar deadlift or kettlebell deadlift':ref('Trap-bar / kettlebell deadlift',['Set the weight over mid-foot and brace.','Hinge and bend the knees enough to reach the handles.','Push the floor away and stand tall.','Lower under control by sending hips back.'],'Keep reps crisp; no grinding or rounded-back pulls.'),
  'Split squat':ref('Split squat',['Take a comfortable staggered stance.','Drop straight down while keeping the front foot planted.','Let the front knee track naturally over the toes.','Drive through the front leg to return.'],'Use support if balance limits the leg work.'),
  'DB bench press':ref('Dumbbell bench press',['Lie with feet planted and shoulder blades supported by the bench.','Keep wrists stacked over elbows.','Lower dumbbells toward the sides of your chest.','Press smoothly without bouncing.'],'Use a neutral or semi-neutral grip if that feels better on shoulders/wrists.'),
  'Half-kneeling single-arm cable/DB press':ref('Half-kneeling single-arm press',['Kneel with one knee down and opposite foot forward.','Brace ribs over pelvis and squeeze the down-knee-side glute.','Press one arm overhead or forward without leaning.','Lower slowly.'],'Keep the trunk quiet; do not compensate with low-back extension.'),
  'Face pull':ref('Face pull',['Set cable/band around face height.','Pull toward your forehead while separating your hands.','Finish with shoulder blades back and elbows high.'],'Keep neck relaxed and avoid shrugging.'),
  'Dead bug':ref('Dead bug',['Lie on your back with hips/knees at 90 degrees and arms up.','Gently flatten ribs and keep low back controlled.','Slowly extend the opposite arm and leg.','Return and alternate.'],'Only move as far as you can without your back arching.'),
  'Suitcase carry':ref('Suitcase carry',['Hold one weight at your side.','Stand tall and walk slowly.','Resist the weight pulling you sideways.'],'Think “zipper straight up the middle”; do not lean away from the load.'),
  'Reverse lunge or supported rear-foot split squat':ref('Reverse lunge / supported split squat',['Step one foot backward and lower under control.','Keep most of the work on the front leg.','Drive through the front foot to return.','Use light support if balance is the limiting factor.'],'Prioritize knee/hip control over depth.'),
  'Single-leg RDL':ref('Single-leg Romanian deadlift',['Stand on one leg with a slight knee bend.','Reach the free leg backward as your torso tips forward.','Keep hips square to the floor.','Drive the stance hip forward to stand.'],'Hold a support at first if balance prevents good hinging.'),
  'Cable row or chest-supported DB row':ref('Row variation',['Keep chest supported or torso stable.','Pull elbows toward the ribs and pause briefly.','Lower the weight under control.'],'Avoid shrugging or yanking the weight.'),
  'Push-up progression':ref('Push-up progression',['Start at the easiest level that is comfortable: wall → counter/bench → floor on handles → flat palms.','Keep body in one straight line and hands under/just outside shoulders.','Lower chest under control and press away.','Stop 2–3 reps before failure.'],'For wrist conditioning, gradually increase flat-palm exposure rather than jumping straight to high reps.'),
  'Cable chop/lift':ref('Cable chop / lift',['Stand athletic and brace your trunk.','Move the handle diagonally across the body.','Allow controlled hip/trunk rotation while keeping knees stable.','Return slowly.'],'Use the torso and hips together; do not yank with the arms.'),
  'Bike/row intervals':ref('Bike / row intervals',['Warm up first.','Work briskly for 30 seconds at an effort you can repeat.','Recover easily for 60 seconds.','Repeat the planned number of rounds.'],'Phase 1 is not all-out sprinting; the last interval should look like the first.'),
  'Short-lever Copenhagen plank':ref('Short-lever Copenhagen plank',['Place the inside of your top knee on a bench.','Support yourself on your forearm.','Lift hips so shoulders, hips and knees form a line.','Hold while breathing normally.'],'Start short-lever on the knee; no sharp groin pain.'),
  'Controlled lateral lunge / shallow Cossack':ref('Lateral lunge / shallow Cossack',['Take a wide stance.','Shift hips toward one side while that knee bends.','Keep the opposite leg long and both feet controlled.','Return to center and repeat.'],'Stay shallow at first; build range only as the groin stays comfortable.'),
  'Calf raise':ref('Calf raise',['Stand tall holding support if needed.','Rise onto the balls of your feet.','Pause briefly at the top.','Lower slowly through a comfortable range.'],'Keep pressure even across the forefoot.'),
  'Tibialis raise':ref('Tibialis raise',['Lean your back against a wall with feet slightly forward.','Keep heels planted and lift toes/forefoot toward shins.','Lower slowly.'],'You should feel the muscles on the front of the lower leg.'),
  'Wrist extension rock':ref('Wrist extension rock',['Start on hands and knees with palms flat.','Fingers point forward; elbows stay straight but relaxed.','Shift shoulders forward gradually.','Rock back before pain and repeat.'],'Progress by increasing the amount of body weight, not by forcing range.'),
  'Light wrist flexion/extension':ref('Wrist flexion / extension',['Support your forearm on a bench or thigh.','Let the hand move freely off the edge.','Use a very light dumbbell to curl the wrist up and lower slowly.','Turn the forearm over to train the opposite direction.'],'Small muscles respond well to slow, light work; avoid sharp ulnar-sided wrist pain.'),
  'Forearm pronation/supination':ref('Forearm pronation / supination',['Hold a light hammer or dumbbell by one end.','Keep elbow bent about 90 degrees and tucked to your side.','Slowly rotate palm up, then palm down.','Control the lever in both directions.'],'Start very light because leverage makes this harder than it looks.'),
  'Band external rotation':ref('Band external rotation',['Keep elbow bent 90 degrees at your side.','Hold a light band and rotate the forearm outward without letting elbow drift.','Return slowly.'],'Keep shoulder blade controlled and use a light band.')
};
function ref(title,steps,watch){return {title,steps,watch}}

const KEY='outdoorAthleteStateV1';
let state=load();
let route='today';
function defaults(){return {week:1,nextSession:'A',logs:[],rideTomorrow:false,energy:3,soreness:1,jointIssue:'',notes:'',bodyWeight:'',lastUpdated:null}}
function load(){try{return {...defaults(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return defaults()}}
function save(){state.lastUpdated=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function fmtDate(iso){return new Date(iso).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function currentPhase(){const w=+state.week; if(w<=2)return PLAN.phases[0]; if(w<=4)return PLAN.phases[1]; if(w<=6)return PLAN.phases[2]; if(w<=8)return PLAN.phases[3]; if(w===9)return PLAN.phases[4]; if(w<=11)return PLAN.phases[5]; return PLAN.phases[6]}
function setTitle(t){document.getElementById('pageTitle').textContent=t}
function render(){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===route)); if(route==='today')renderToday(); if(route==='plan')renderPlan(); if(route==='library')renderLibrary(); if(route==='history')renderHistory(); if(route==='settings')renderSettings()}

function renderToday(){setTitle('Today'); const p=currentPhase(); const s=PLAN.sessions[state.nextSession]; const wkLogs=state.logs.filter(l=>weekOf(l.date)===weekOf(new Date().toISOString()));
 const banner=state.rideTomorrow?'<div class="notice"><b>Ride tomorrow:</b> reduce lower-body volume ~⅓ and skip intervals.</div>':'';
 document.getElementById('app').innerHTML=`<div class="grid">
 <section class="card hero"><div class="small muted">WEEK ${state.week} • ${esc(p[1])}</div><div class="big">${esc(s.name)}</div><div class="muted">${esc(s.subtitle)}</div><div class="meta"><span class="pill good">${wkLogs.length} sessions logged this week</span><span class="pill">~55–60 min</span></div><button class="primary full" onclick="startWorkout('${state.nextSession}')">Start workout</button></section>
 ${banner}
 <section class="card"><h3>Quick check-in</h3><div class="two grid"><div><label>Energy (1–5)</label><select id="energy" onchange="quickSave()">${[1,2,3,4,5].map(n=>`<option ${state.energy==n?'selected':''}>${n}</option>`).join('')}</select></div><div><label>Soreness (1–5)</label><select id="soreness" onchange="quickSave()">${[1,2,3,4,5].map(n=>`<option ${state.soreness==n?'selected':''}>${n}</option>`).join('')}</select></div></div><div style="margin-top:10px"><label><input type="checkbox" id="rideTomorrow" ${state.rideTomorrow?'checked':''} onchange="quickSave()"> Hard ride/outdoor day tomorrow</label></div><div style="margin-top:10px"><label>Joint/sensitivity note (optional)</label><input id="jointIssue" value="${esc(state.jointIssue)}" onchange="quickSave()" placeholder="e.g., wrist a little sensitive"></div></section>
 <section class="card"><div class="row space"><div><h3>This phase</h3><div class="muted small">${esc(p[0])}</div></div><span class="pill">RPE focus</span></div><p>${esc(p[2])}</p><div class="goodbox">${esc(p[3])}</div></section>
 <section class="card"><h3>Weekly target</h3><div class="stat-grid"><div class="stat"><b>3</b><span>strength</span></div><div class="stat"><b>2–3</b><span>outdoor days</span></div><div class="stat"><b>1</b><span>full rest day</span></div></div></section>
 </div>`}
function quickSave(){state.energy=+document.getElementById('energy').value;state.soreness=+document.getElementById('soreness').value;state.rideTomorrow=document.getElementById('rideTomorrow').checked;state.jointIssue=document.getElementById('jointIssue').value;save();renderToday()}

function startWorkout(code){const s=PLAN.sessions[code]; const previous=findLastSession(code); const initialSets=(state.week<=2?2:3); let html=`<form method="dialog"><div class="row space"><div><div class="eyebrow">WEEK ${state.week}</div><h2>${esc(s.name)}</h2><div class="muted">${esc(s.subtitle)}</div></div><button class="secondary" value="cancel">Close</button></div></form>`;
 html+=state.rideTomorrow?'<div class="notice" style="margin:12px 0">Ride tomorrow: consider fewer lower-body sets and skip intervals.</div>':'';
 html+=`<details class="card" style="margin:12px 0"><summary><b>8–10 min warm-up</b></summary><div class="reference-list">${PLAN.warmup.map(x=>`<button type="button" class="reference-row" onclick='showReference(${JSON.stringify(x)})'><span>${esc(x)}</span><span class="chev">›</span></button>`).join('')}</div></details>`;
 html+=`<div id="workoutForm">${s.exercises.map((e,idx)=>exerciseLogHtml(e,idx,previous,initialSets)).join('')}</div>`;
 html+=`<div class="card" style="margin-top:12px"><label>Session notes</label><textarea id="sessionNotes" rows="3" placeholder="What felt good? Anything sensitive?"></textarea><div class="two grid" style="margin-top:10px"><div><label>Session RPE</label><select id="sessionRpe">${[5,6,7,8,9].map(n=>`<option ${n===7?'selected':''}>${n}</option>`).join('')}</select></div><div><label>Energy</label><select id="sessionEnergy">${[1,2,3,4,5].map(n=>`<option ${n===state.energy?'selected':''}>${n}</option>`).join('')}</select></div></div><button class="primary full" style="margin-top:12px" onclick="finishWorkout('${code}')">Finish & save workout</button></div>`;
 showModal(html)}
function exerciseLogHtml(e,idx,previous,sets){const prev=previous?.exercises?.find(x=>x.name===e.name); const last=prev?.sets?.find(x=>x.weight)?.weight||''; return `<section class="card exercise"><button type="button" class="exercise-link" onclick='showReference(${JSON.stringify(e.name)})'><span class="exercise-title">${esc(e.name)}</span><span class="chev">›</span></button><div class="meta"><span class="pill">${esc(e.prescription)}</span><span class="pill">${esc(e.effort)}</span><span class="pill">Rest ${esc(e.rest)}</span></div><div class="small muted">${esc(e.cue)}</div>${last?`<div class="small" style="margin-top:8px">Last load: <b>${esc(last)}</b></div>`:''}<div>${Array.from({length:sets},(_,s)=>`<div class="set-row"><div class="set-badge">${s+1}</div><input class="w-${idx}" placeholder="lb" inputmode="decimal"><input class="r-${idx}" placeholder="reps" inputmode="numeric"><label class="done-check"><input class="d-${idx}" type="checkbox"></label></div>`).join('')}</div></section>`}
function finishWorkout(code){const sess=PLAN.sessions[code]; const exLogs=sess.exercises.map((e,idx)=>{const ws=[...document.querySelectorAll('.w-'+idx)];const rs=[...document.querySelectorAll('.r-'+idx)];const ds=[...document.querySelectorAll('.d-'+idx)];return {name:e.name,sets:ws.map((w,i)=>({weight:w.value,reps:rs[i].value,done:ds[i].checked}))}}); const log={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(),date:new Date().toISOString(),week:+state.week,session:code,name:sess.name,energy:+document.getElementById('sessionEnergy').value,rpe:+document.getElementById('sessionRpe').value,notes:document.getElementById('sessionNotes').value,exercises:exLogs}; state.logs.unshift(log); state.nextSession=code==='A'?'B':code==='B'?'C':'A'; save(); document.getElementById('modal').close(); render();}
function findLastSession(code){return state.logs.find(l=>l.session===code)}

function showReference(name){const item=REFERENCES[name]||ref(name,['Follow the programmed prescription with controlled technique.'],'Use a comfortable range and stop if you feel sharp pain.'); const q=encodeURIComponent(item.title+' exercise technique'); const html=`<form method="dialog"><div class="row space"><div><div class="eyebrow">EXERCISE REFERENCE</div><h2>${esc(item.title)}</h2></div><button class="secondary" value="close">Close</button></div></form><h3>How to do it</h3><ol class="steps">${item.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="goodbox"><b>Key cue:</b> ${esc(item.watch)}</div><a class="secondary full demo-link" href="https://www.youtube.com/results?search_query=${q}" target="_blank" rel="noopener">Search video demos ↗</a>`; showDetail(html)}

function renderPlan(){setTitle('Plan'); const p=currentPhase(); document.getElementById('app').innerHTML=`<div class="grid"><section class="card hero"><div class="small muted">CURRENT</div><div class="big">Week ${state.week}</div><div>${esc(p[1])}</div><div style="margin-top:12px"><label>Change week</label><input type="range" min="1" max="12" value="${state.week}" oninput="setWeek(this.value)"><div class="row space small muted"><span>1</span><span>12</span></div></div></section><section class="card"><h3>12-week progression</h3>${PLAN.phases.map(ph=>`<div class="history-item"><b>${esc(ph[0])} — ${esc(ph[1])}</b><div class="small muted">${esc(ph[2])}</div><div class="small">${esc(ph[3])}</div></div>`).join('')}</section>${Object.entries(PLAN.sessions).map(([k,s])=>`<section class="card"><div class="row space"><div><h3>${esc(s.name)}</h3><div class="muted">${esc(s.subtitle)}</div></div><button class="secondary" onclick="startWorkout('${k}')">Open</button></div><div style="margin-top:10px">${s.exercises.map(e=>`<button type="button" class="reference-row plan-ref" onclick='showReference(${JSON.stringify(e.name)})'><span><b>${esc(e.name)}</b><small>${esc(e.prescription)} • ${esc(e.effort)}</small></span><span class="chev">›</span></button>`).join('')}</div></section>`).join('')}</div>`}
function setWeek(v){state.week=+v;save();renderPlan()}

function renderLibrary(){setTitle('Library'); const all=[...Object.values(PLAN.sessions).flatMap(s=>s.exercises),...PLAN.durability]; document.getElementById('app').innerHTML=`<div class="grid"><section class="card"><input id="search" placeholder="Search exercises" oninput="filterLib(this.value)"></section><section class="card"><h3>Joint durability</h3><p class="small muted">Short permanent maintenance work for wrists, groin/adductors, ankles and shoulders.</p>${PLAN.durability.map((e,i)=>libItem(e,'d'+i)).join('')}</section><section class="card"><h3>Exercise library</h3><div id="libItems">${all.map((e,i)=>libItem(e,'a'+i)).join('')}</div></section></div>`}
function libItem(e,id){return `<button type="button" class="history-item lib reference-row" data-search="${esc((e.name+' '+e.cue).toLowerCase())}" onclick='showReference(${JSON.stringify(e.name)})'><span><b>${esc(e.name)}</b><small>${esc(e.prescription)} • ${esc(e.effort)} • rest ${esc(e.rest)}</small><small>${esc(e.cue)}</small></span><span class="chev">›</span></button>`}
function filterLib(q){q=q.toLowerCase();document.querySelectorAll('.lib').forEach(x=>x.style.display=x.dataset.search.includes(q)?'flex':'none')}

function renderHistory(){setTitle('History'); const weekCount=state.logs.filter(l=>weekOf(l.date)===weekOf(new Date().toISOString())).length; const total=state.logs.length; const avg=total?(state.logs.reduce((a,b)=>a+b.energy,0)/total).toFixed(1):'—'; document.getElementById('app').innerHTML=`<div class="grid"><section class="card"><div class="stat-grid"><div class="stat"><b>${weekCount}</b><span>this week</span></div><div class="stat"><b>${total}</b><span>total sessions</span></div><div class="stat"><b>${avg}</b><span>avg energy</span></div></div></section><section class="card"><h3>Workout history</h3>${state.logs.length?state.logs.map(l=>`<button type="button" class="history-item history-open" onclick='openHistory(${JSON.stringify(l.id)})'><div class="row space"><div><b>${esc(l.name)}</b><div class="small muted">${fmtDate(l.date)} • Week ${l.week}</div></div><div class="row"><div class="score">RPE ${l.rpe}</div><span class="chev">›</span></div></div>${l.notes?`<div class="small history-note">${esc(l.notes)}</div>`:''}</button>`).join(''):'<p class="muted">No workouts logged yet.</p>'}</section></div>`}
function openHistory(id){const l=state.logs.find(x=>x.id===id); if(!l)return; const html=`<form method="dialog"><div class="row space"><div><div class="eyebrow">WORKOUT HISTORY</div><h2>${esc(l.name)}</h2><div class="muted">${fmtDate(l.date)} • Week ${l.week}</div></div><button class="secondary" value="close">Close</button></div></form><div class="meta"><span class="pill">RPE ${l.rpe}</span><span class="pill">Energy ${l.energy}/5</span></div>${l.notes?`<div class="card compact"><b>Notes</b><div class="small" style="margin-top:5px">${esc(l.notes)}</div></div>`:''}<div class="history-detail">${l.exercises.map(e=>`<section class="card compact"><button type="button" class="exercise-link" onclick='showReference(${JSON.stringify(e.name)})'><span><b>${esc(e.name)}</b></span><span class="chev">›</span></button>${e.sets.map((s,i)=>`<div class="saved-set"><span>Set ${i+1}</span><span>${s.weight?esc(s.weight)+' lb':'—'} × ${s.reps?esc(s.reps)+' reps':'—'} ${s.done?'✓':''}</span></div>`).join('')}</section>`).join('')}</div>`; showDetail(html)}

function renderSettings(){setTitle('Settings'); document.getElementById('app').innerHTML=`<div class="grid"><section class="card"><h3>App settings</h3><label>Current week</label><select onchange="setWeekSetting(this.value)">${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${state.week===i+1?'selected':''}>Week ${i+1}</option>`).join('')}</select><label style="margin-top:12px">Body weight (optional)</label><input value="${esc(state.bodyWeight)}" onchange="state.bodyWeight=this.value;save()" placeholder="lb"></section><section class="card"><h3>Backup & restore</h3><p class="small muted">V1 stores your data on this device. Export a backup periodically before clearing browser data or changing phones.</p><div class="stack"><button class="secondary full" onclick="exportData()">Export backup (.json)</button><label class="secondary full" style="text-align:center;color:var(--text)">Import backup<input type="file" accept="application/json" style="display:none" onchange="importData(this.files[0])"></label></div></section><section class="card"><h3>Install on iPhone</h3><p class="small">Open the hosted app in Chrome → tap <b>Share</b> → <b>Add to Home Screen</b>. After installation, launch it from the Home Screen like an app.</p></section><section class="card"><h3>Version</h3><p class="small muted">Outdoor Athlete v${PLAN.version}</p></section><section class="card"><h3>V1 principles</h3><p class="small muted">Outdoor performance first. No failure training. Riding counts as training load. Pain changes range/load/exercise instead of forcing the plan.</p></section><button class="danger full" onclick="resetApp()">Reset all local data</button></div>`}
function setWeekSetting(v){state.week=+v;save();renderSettings()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='outdoor-athlete-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{state={...defaults(),...JSON.parse(r.result)};save();renderSettings();alert('Backup restored.')}catch{alert('That file could not be imported.')}};r.readAsText(file)}
function resetApp(){if(confirm('Reset all workout history and settings?')){state=defaults();save();render()}}
function weekOf(iso){const d=new Date(iso), day=(d.getDay()+6)%7; d.setHours(0,0,0,0); d.setDate(d.getDate()-day); return d.toISOString().slice(0,10)}
function showModal(html){const m=document.getElementById('modal');m.innerHTML=html;m.showModal()}
function showDetail(html){const m=document.getElementById('detailModal');m.innerHTML=html;m.showModal()}

document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>{route=b.dataset.route;render()}));
document.getElementById('installHelpBtn').addEventListener('click',()=>showDetail(`<form method="dialog"><div class="row space"><h2>Add to iPhone</h2><button class="secondary" value="close">Close</button></div></form><p>Once this app is hosted at an HTTPS address:</p><ol><li>Open it in <b>Chrome</b> on your iPhone.</li><li>Tap the <b>Share</b> icon.</li><li>Choose <b>Add to Home Screen</b>.</li><li>Launch <b>Outdoor Athlete</b> from the new icon.</li></ol><p class="small muted">Workout data stays on your device in V1, so use Settings → Export backup occasionally.</p>`));
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
render();
